//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsBehdadWebServices.AllotmentService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class UnableToAuthenticateException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class credential : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidCredentialException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidAllotmentItemInfoException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidDateException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidAllotmentCodeException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class PageSizeIsTooMuchException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class UnableToAllotException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidTransactionIdException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class AllotmentAmountIsMoreThanTransactionAmountException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidTransactionForAllotmentException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidAllotmentAmountTypeException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidAllotmentException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class TransactionAlreadyAllotedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="com.misc.bis.behdad.service", ConfigurationName="AllotmentService.AllotmentService")]
    public interface AllotmentService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsBehdadWebServices.AllotmentService.getAllotmentAccountsResponse getAllotmentAccounts(WindowsBehdadWebServices.AllotmentService.getAllotmentAccounts request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.getAllotmentAccountsResponse> getAllotmentAccountsAsync(WindowsBehdadWebServices.AllotmentService.getAllotmentAccounts request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidAllotmentItemInfoException), Action="", Name="InvalidAllotmentItemInfoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidDateException), Action="", Name="InvalidDateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidAllotmentCodeException), Action="", Name="InvalidAllotmentCodeException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsBehdadWebServices.AllotmentService.addAllotmentInfoResponse addAllotmentInfo(WindowsBehdadWebServices.AllotmentService.addAllotmentInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.addAllotmentInfoResponse> addAllotmentInfoAsync(WindowsBehdadWebServices.AllotmentService.addAllotmentInfo request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidDateException), Action="", Name="InvalidDateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.PageSizeIsTooMuchException), Action="", Name="PageSizeIsTooMuchException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsBehdadWebServices.AllotmentService.getAllotmentTransactionsResponse getAllotmentTransactions(WindowsBehdadWebServices.AllotmentService.getAllotmentTransactions request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.getAllotmentTransactionsResponse> getAllotmentTransactionsAsync(WindowsBehdadWebServices.AllotmentService.getAllotmentTransactions request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsBehdadWebServices.AllotmentService.getAllotmentInfoListResponse getAllotmentInfoList(WindowsBehdadWebServices.AllotmentService.getAllotmentInfoList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.getAllotmentInfoListResponse> getAllotmentInfoListAsync(WindowsBehdadWebServices.AllotmentService.getAllotmentInfoList request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsBehdadWebServices.AllotmentService.removeAllotmentInfoResponse removeAllotmentInfo(WindowsBehdadWebServices.AllotmentService.removeAllotmentInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.removeAllotmentInfoResponse> removeAllotmentInfoAsync(WindowsBehdadWebServices.AllotmentService.removeAllotmentInfo request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.UnableToAllotException), Action="", Name="UnableToAllotException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidTransactionIdException), Action="", Name="InvalidTransactionIdException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.AllotmentAmountIsMoreThanTransactionAmountException), Action="", Name="AllotmentAmountIsMoreThanTransactionAmountException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidTransactionForAllotmentException), Action="", Name="InvalidTransactionForAllotmentException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidAllotmentAmountTypeException), Action="", Name="InvalidAllotmentAmountTypeException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidAllotmentException), Action="", Name="InvalidAllotmentException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.TransactionAlreadyAllotedException), Action="", Name="TransactionAlreadyAllotedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsBehdadWebServices.AllotmentService.doManualAllotmentResponse doManualAllotment(WindowsBehdadWebServices.AllotmentService.doManualAllotment request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.doManualAllotmentResponse> doManualAllotmentAsync(WindowsBehdadWebServices.AllotmentService.doManualAllotment request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AllotmentService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsBehdadWebServices.AllotmentService.getAllotmentInfoResponse getAllotmentInfo(WindowsBehdadWebServices.AllotmentService.getAllotmentInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.getAllotmentInfoResponse> getAllotmentInfoAsync(WindowsBehdadWebServices.AllotmentService.getAllotmentInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllotmentAccounts", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getAllotmentAccounts {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.credential arg0;
        
        public getAllotmentAccounts() {
        }
        
        public getAllotmentAccounts(WindowsBehdadWebServices.AllotmentService.credential arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllotmentAccountsResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getAllotmentAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getAllotmentAccountsResponse() {
        }
        
        public getAllotmentAccountsResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class allotmentInfoDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string allotmentCodeField;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private allotmentAmountType amountTypeField;
        
        private bool amountTypeFieldSpecified;
        
        private string descriptionField;
        
        private string destAccountNumberField;
        
        private string endDateField;
        
        private string incomeIndexCodeField;
        
        private string incomeSubsidiaryCodeField;
        
        private string organCustomCodeField;
        
        private string sourceAccountNumberField;
        
        private string startDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string allotmentCode {
            get {
                return this.allotmentCodeField;
            }
            set {
                this.allotmentCodeField = value;
                this.RaisePropertyChanged("allotmentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public allotmentAmountType amountType {
            get {
                return this.amountTypeField;
            }
            set {
                this.amountTypeField = value;
                this.RaisePropertyChanged("amountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountTypeSpecified {
            get {
                return this.amountTypeFieldSpecified;
            }
            set {
                this.amountTypeFieldSpecified = value;
                this.RaisePropertyChanged("amountTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string destAccountNumber {
            get {
                return this.destAccountNumberField;
            }
            set {
                this.destAccountNumberField = value;
                this.RaisePropertyChanged("destAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string incomeIndexCode {
            get {
                return this.incomeIndexCodeField;
            }
            set {
                this.incomeIndexCodeField = value;
                this.RaisePropertyChanged("incomeIndexCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string incomeSubsidiaryCode {
            get {
                return this.incomeSubsidiaryCodeField;
            }
            set {
                this.incomeSubsidiaryCodeField = value;
                this.RaisePropertyChanged("incomeSubsidiaryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string organCustomCode {
            get {
                return this.organCustomCodeField;
            }
            set {
                this.organCustomCodeField = value;
                this.RaisePropertyChanged("organCustomCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string sourceAccountNumber {
            get {
                return this.sourceAccountNumberField;
            }
            set {
                this.sourceAccountNumberField = value;
                this.RaisePropertyChanged("sourceAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public enum allotmentAmountType {
        
        /// <remarks/>
        PERCENT,
        
        /// <remarks/>
        MONETARY,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAllotmentInfo", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class addAllotmentInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.credential arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.allotmentInfoDetail arg1;
        
        public addAllotmentInfo() {
        }
        
        public addAllotmentInfo(WindowsBehdadWebServices.AllotmentService.credential arg0, WindowsBehdadWebServices.AllotmentService.allotmentInfoDetail arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAllotmentInfoResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class addAllotmentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long @return;
        
        public addAllotmentInfoResponse() {
        }
        
        public addAllotmentInfoResponse(long @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class allotmentTransactionFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNumberField;
        
        private string fromDateTimeField;
        
        private string paymentIdentifierField;
        
        private string toDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fromDateTime {
            get {
                return this.fromDateTimeField;
            }
            set {
                this.fromDateTimeField = value;
                this.RaisePropertyChanged("fromDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string paymentIdentifier {
            get {
                return this.paymentIdentifierField;
            }
            set {
                this.paymentIdentifierField = value;
                this.RaisePropertyChanged("paymentIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string toDateTime {
            get {
                return this.toDateTimeField;
            }
            set {
                this.toDateTimeField = value;
                this.RaisePropertyChanged("toDateTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class paging : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pageNumberField;
        
        private bool pageNumberFieldSpecified;
        
        private int recordCountField;
        
        private bool recordCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
                this.RaisePropertyChanged("pageNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNumberSpecified {
            get {
                return this.pageNumberFieldSpecified;
            }
            set {
                this.pageNumberFieldSpecified = value;
                this.RaisePropertyChanged("pageNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
                this.RaisePropertyChanged("recordCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recordCountSpecified {
            get {
                return this.recordCountFieldSpecified;
            }
            set {
                this.recordCountFieldSpecified = value;
                this.RaisePropertyChanged("recordCountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class pagedData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] currentPageDataField;
        
        private int pageIndexField;
        
        private bool pageIndexFieldSpecified;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private long totalCountField;
        
        private bool totalCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("currentPageData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public object[] currentPageData {
            get {
                return this.currentPageDataField;
            }
            set {
                this.currentPageDataField = value;
                this.RaisePropertyChanged("currentPageData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int pageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
                this.RaisePropertyChanged("pageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageIndexSpecified {
            get {
                return this.pageIndexFieldSpecified;
            }
            set {
                this.pageIndexFieldSpecified = value;
                this.RaisePropertyChanged("pageIndexSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified {
            get {
                return this.pageSizeFieldSpecified;
            }
            set {
                this.pageSizeFieldSpecified = value;
                this.RaisePropertyChanged("pageSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long totalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
                this.RaisePropertyChanged("totalCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCountSpecified {
            get {
                return this.totalCountFieldSpecified;
            }
            set {
                this.totalCountFieldSpecified = value;
                this.RaisePropertyChanged("totalCountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllotmentTransactions", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getAllotmentTransactions {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.credential arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.allotmentTransactionFilter arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.paging arg2;
        
        public getAllotmentTransactions() {
        }
        
        public getAllotmentTransactions(WindowsBehdadWebServices.AllotmentService.credential arg0, WindowsBehdadWebServices.AllotmentService.allotmentTransactionFilter arg1, WindowsBehdadWebServices.AllotmentService.paging arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllotmentTransactionsResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getAllotmentTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.pagedData @return;
        
        public getAllotmentTransactionsResponse() {
        }
        
        public getAllotmentTransactionsResponse(WindowsBehdadWebServices.AllotmentService.pagedData @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class allotmentFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNumberField;
        
        private string allotmentCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string allotmentCode {
            get {
                return this.allotmentCodeField;
            }
            set {
                this.allotmentCodeField = value;
                this.RaisePropertyChanged("allotmentCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class allotmentInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activeField;
        
        private bool activeFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private allotmentAmountType amountTypeField;
        
        private bool amountTypeFieldSpecified;
        
        private string destAccountNumberField;
        
        private string endDateField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string startDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
                this.RaisePropertyChanged("activeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public allotmentAmountType amountType {
            get {
                return this.amountTypeField;
            }
            set {
                this.amountTypeField = value;
                this.RaisePropertyChanged("amountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountTypeSpecified {
            get {
                return this.amountTypeFieldSpecified;
            }
            set {
                this.amountTypeFieldSpecified = value;
                this.RaisePropertyChanged("amountTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string destAccountNumber {
            get {
                return this.destAccountNumberField;
            }
            set {
                this.destAccountNumberField = value;
                this.RaisePropertyChanged("destAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllotmentInfoList", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getAllotmentInfoList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.credential arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.allotmentFilter arg1;
        
        public getAllotmentInfoList() {
        }
        
        public getAllotmentInfoList(WindowsBehdadWebServices.AllotmentService.credential arg0, WindowsBehdadWebServices.AllotmentService.allotmentFilter arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllotmentInfoListResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getAllotmentInfoListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.allotmentInfo[] @return;
        
        public getAllotmentInfoListResponse() {
        }
        
        public getAllotmentInfoListResponse(WindowsBehdadWebServices.AllotmentService.allotmentInfo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeAllotmentInfo", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class removeAllotmentInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.credential arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long allotmentInformationId;
        
        public removeAllotmentInfo() {
        }
        
        public removeAllotmentInfo(WindowsBehdadWebServices.AllotmentService.credential arg0, long allotmentInformationId) {
            this.arg0 = arg0;
            this.allotmentInformationId = allotmentInformationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeAllotmentInfoResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class removeAllotmentInfoResponse {
        
        public removeAllotmentInfoResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class manualAllotmentInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private allotmentAmountType amountTypeField;
        
        private bool amountTypeFieldSpecified;
        
        private string descriptionField;
        
        private string destAccountNumberField;
        
        private string paymentIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public allotmentAmountType amountType {
            get {
                return this.amountTypeField;
            }
            set {
                this.amountTypeField = value;
                this.RaisePropertyChanged("amountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountTypeSpecified {
            get {
                return this.amountTypeFieldSpecified;
            }
            set {
                this.amountTypeFieldSpecified = value;
                this.RaisePropertyChanged("amountTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string destAccountNumber {
            get {
                return this.destAccountNumberField;
            }
            set {
                this.destAccountNumberField = value;
                this.RaisePropertyChanged("destAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string paymentIdentifier {
            get {
                return this.paymentIdentifierField;
            }
            set {
                this.paymentIdentifierField = value;
                this.RaisePropertyChanged("paymentIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doManualAllotment", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class doManualAllotment {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.credential arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long transactionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("manualAllotmentInfoList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.manualAllotmentInfo[] manualAllotmentInfoList;
        
        public doManualAllotment() {
        }
        
        public doManualAllotment(WindowsBehdadWebServices.AllotmentService.credential arg0, long transactionId, WindowsBehdadWebServices.AllotmentService.manualAllotmentInfo[] manualAllotmentInfoList) {
            this.arg0 = arg0;
            this.transactionId = transactionId;
            this.manualAllotmentInfoList = manualAllotmentInfoList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doManualAllotmentResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class doManualAllotmentResponse {
        
        public doManualAllotmentResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllotmentInfo", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getAllotmentInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.credential arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long allotmentInformationId;
        
        public getAllotmentInfo() {
        }
        
        public getAllotmentInfo(WindowsBehdadWebServices.AllotmentService.credential arg0, long allotmentInformationId) {
            this.arg0 = arg0;
            this.allotmentInformationId = allotmentInformationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllotmentInfoResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getAllotmentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AllotmentService.allotmentInfoDetail @return;
        
        public getAllotmentInfoResponse() {
        }
        
        public getAllotmentInfoResponse(WindowsBehdadWebServices.AllotmentService.allotmentInfoDetail @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AllotmentServiceChannel : WindowsBehdadWebServices.AllotmentService.AllotmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllotmentServiceClient : System.ServiceModel.ClientBase<WindowsBehdadWebServices.AllotmentService.AllotmentService>, WindowsBehdadWebServices.AllotmentService.AllotmentService {
        
        public AllotmentServiceClient() {
        }
        
        public AllotmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllotmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllotmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllotmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AllotmentService.getAllotmentAccountsResponse WindowsBehdadWebServices.AllotmentService.AllotmentService.getAllotmentAccounts(WindowsBehdadWebServices.AllotmentService.getAllotmentAccounts request) {
            return base.Channel.getAllotmentAccounts(request);
        }
        
        public string[] getAllotmentAccounts(WindowsBehdadWebServices.AllotmentService.credential arg0) {
            WindowsBehdadWebServices.AllotmentService.getAllotmentAccounts inValue = new WindowsBehdadWebServices.AllotmentService.getAllotmentAccounts();
            inValue.arg0 = arg0;
            WindowsBehdadWebServices.AllotmentService.getAllotmentAccountsResponse retVal = ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).getAllotmentAccounts(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.getAllotmentAccountsResponse> WindowsBehdadWebServices.AllotmentService.AllotmentService.getAllotmentAccountsAsync(WindowsBehdadWebServices.AllotmentService.getAllotmentAccounts request) {
            return base.Channel.getAllotmentAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.getAllotmentAccountsResponse> getAllotmentAccountsAsync(WindowsBehdadWebServices.AllotmentService.credential arg0) {
            WindowsBehdadWebServices.AllotmentService.getAllotmentAccounts inValue = new WindowsBehdadWebServices.AllotmentService.getAllotmentAccounts();
            inValue.arg0 = arg0;
            return ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).getAllotmentAccountsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AllotmentService.addAllotmentInfoResponse WindowsBehdadWebServices.AllotmentService.AllotmentService.addAllotmentInfo(WindowsBehdadWebServices.AllotmentService.addAllotmentInfo request) {
            return base.Channel.addAllotmentInfo(request);
        }
        
        public long addAllotmentInfo(WindowsBehdadWebServices.AllotmentService.credential arg0, WindowsBehdadWebServices.AllotmentService.allotmentInfoDetail arg1) {
            WindowsBehdadWebServices.AllotmentService.addAllotmentInfo inValue = new WindowsBehdadWebServices.AllotmentService.addAllotmentInfo();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WindowsBehdadWebServices.AllotmentService.addAllotmentInfoResponse retVal = ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).addAllotmentInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.addAllotmentInfoResponse> WindowsBehdadWebServices.AllotmentService.AllotmentService.addAllotmentInfoAsync(WindowsBehdadWebServices.AllotmentService.addAllotmentInfo request) {
            return base.Channel.addAllotmentInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.addAllotmentInfoResponse> addAllotmentInfoAsync(WindowsBehdadWebServices.AllotmentService.credential arg0, WindowsBehdadWebServices.AllotmentService.allotmentInfoDetail arg1) {
            WindowsBehdadWebServices.AllotmentService.addAllotmentInfo inValue = new WindowsBehdadWebServices.AllotmentService.addAllotmentInfo();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).addAllotmentInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AllotmentService.getAllotmentTransactionsResponse WindowsBehdadWebServices.AllotmentService.AllotmentService.getAllotmentTransactions(WindowsBehdadWebServices.AllotmentService.getAllotmentTransactions request) {
            return base.Channel.getAllotmentTransactions(request);
        }
        
        public WindowsBehdadWebServices.AllotmentService.pagedData getAllotmentTransactions(WindowsBehdadWebServices.AllotmentService.credential arg0, WindowsBehdadWebServices.AllotmentService.allotmentTransactionFilter arg1, WindowsBehdadWebServices.AllotmentService.paging arg2) {
            WindowsBehdadWebServices.AllotmentService.getAllotmentTransactions inValue = new WindowsBehdadWebServices.AllotmentService.getAllotmentTransactions();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            WindowsBehdadWebServices.AllotmentService.getAllotmentTransactionsResponse retVal = ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).getAllotmentTransactions(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.getAllotmentTransactionsResponse> WindowsBehdadWebServices.AllotmentService.AllotmentService.getAllotmentTransactionsAsync(WindowsBehdadWebServices.AllotmentService.getAllotmentTransactions request) {
            return base.Channel.getAllotmentTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.getAllotmentTransactionsResponse> getAllotmentTransactionsAsync(WindowsBehdadWebServices.AllotmentService.credential arg0, WindowsBehdadWebServices.AllotmentService.allotmentTransactionFilter arg1, WindowsBehdadWebServices.AllotmentService.paging arg2) {
            WindowsBehdadWebServices.AllotmentService.getAllotmentTransactions inValue = new WindowsBehdadWebServices.AllotmentService.getAllotmentTransactions();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).getAllotmentTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AllotmentService.getAllotmentInfoListResponse WindowsBehdadWebServices.AllotmentService.AllotmentService.getAllotmentInfoList(WindowsBehdadWebServices.AllotmentService.getAllotmentInfoList request) {
            return base.Channel.getAllotmentInfoList(request);
        }
        
        public WindowsBehdadWebServices.AllotmentService.allotmentInfo[] getAllotmentInfoList(WindowsBehdadWebServices.AllotmentService.credential arg0, WindowsBehdadWebServices.AllotmentService.allotmentFilter arg1) {
            WindowsBehdadWebServices.AllotmentService.getAllotmentInfoList inValue = new WindowsBehdadWebServices.AllotmentService.getAllotmentInfoList();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WindowsBehdadWebServices.AllotmentService.getAllotmentInfoListResponse retVal = ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).getAllotmentInfoList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.getAllotmentInfoListResponse> WindowsBehdadWebServices.AllotmentService.AllotmentService.getAllotmentInfoListAsync(WindowsBehdadWebServices.AllotmentService.getAllotmentInfoList request) {
            return base.Channel.getAllotmentInfoListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.getAllotmentInfoListResponse> getAllotmentInfoListAsync(WindowsBehdadWebServices.AllotmentService.credential arg0, WindowsBehdadWebServices.AllotmentService.allotmentFilter arg1) {
            WindowsBehdadWebServices.AllotmentService.getAllotmentInfoList inValue = new WindowsBehdadWebServices.AllotmentService.getAllotmentInfoList();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).getAllotmentInfoListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AllotmentService.removeAllotmentInfoResponse WindowsBehdadWebServices.AllotmentService.AllotmentService.removeAllotmentInfo(WindowsBehdadWebServices.AllotmentService.removeAllotmentInfo request) {
            return base.Channel.removeAllotmentInfo(request);
        }
        
        public void removeAllotmentInfo(WindowsBehdadWebServices.AllotmentService.credential arg0, long allotmentInformationId) {
            WindowsBehdadWebServices.AllotmentService.removeAllotmentInfo inValue = new WindowsBehdadWebServices.AllotmentService.removeAllotmentInfo();
            inValue.arg0 = arg0;
            inValue.allotmentInformationId = allotmentInformationId;
            WindowsBehdadWebServices.AllotmentService.removeAllotmentInfoResponse retVal = ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).removeAllotmentInfo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.removeAllotmentInfoResponse> WindowsBehdadWebServices.AllotmentService.AllotmentService.removeAllotmentInfoAsync(WindowsBehdadWebServices.AllotmentService.removeAllotmentInfo request) {
            return base.Channel.removeAllotmentInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.removeAllotmentInfoResponse> removeAllotmentInfoAsync(WindowsBehdadWebServices.AllotmentService.credential arg0, long allotmentInformationId) {
            WindowsBehdadWebServices.AllotmentService.removeAllotmentInfo inValue = new WindowsBehdadWebServices.AllotmentService.removeAllotmentInfo();
            inValue.arg0 = arg0;
            inValue.allotmentInformationId = allotmentInformationId;
            return ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).removeAllotmentInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AllotmentService.doManualAllotmentResponse WindowsBehdadWebServices.AllotmentService.AllotmentService.doManualAllotment(WindowsBehdadWebServices.AllotmentService.doManualAllotment request) {
            return base.Channel.doManualAllotment(request);
        }
        
        public void doManualAllotment(WindowsBehdadWebServices.AllotmentService.credential arg0, long transactionId, WindowsBehdadWebServices.AllotmentService.manualAllotmentInfo[] manualAllotmentInfoList) {
            WindowsBehdadWebServices.AllotmentService.doManualAllotment inValue = new WindowsBehdadWebServices.AllotmentService.doManualAllotment();
            inValue.arg0 = arg0;
            inValue.transactionId = transactionId;
            inValue.manualAllotmentInfoList = manualAllotmentInfoList;
            WindowsBehdadWebServices.AllotmentService.doManualAllotmentResponse retVal = ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).doManualAllotment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.doManualAllotmentResponse> WindowsBehdadWebServices.AllotmentService.AllotmentService.doManualAllotmentAsync(WindowsBehdadWebServices.AllotmentService.doManualAllotment request) {
            return base.Channel.doManualAllotmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.doManualAllotmentResponse> doManualAllotmentAsync(WindowsBehdadWebServices.AllotmentService.credential arg0, long transactionId, WindowsBehdadWebServices.AllotmentService.manualAllotmentInfo[] manualAllotmentInfoList) {
            WindowsBehdadWebServices.AllotmentService.doManualAllotment inValue = new WindowsBehdadWebServices.AllotmentService.doManualAllotment();
            inValue.arg0 = arg0;
            inValue.transactionId = transactionId;
            inValue.manualAllotmentInfoList = manualAllotmentInfoList;
            return ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).doManualAllotmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AllotmentService.getAllotmentInfoResponse WindowsBehdadWebServices.AllotmentService.AllotmentService.getAllotmentInfo(WindowsBehdadWebServices.AllotmentService.getAllotmentInfo request) {
            return base.Channel.getAllotmentInfo(request);
        }
        
        public WindowsBehdadWebServices.AllotmentService.allotmentInfoDetail getAllotmentInfo(WindowsBehdadWebServices.AllotmentService.credential arg0, long allotmentInformationId) {
            WindowsBehdadWebServices.AllotmentService.getAllotmentInfo inValue = new WindowsBehdadWebServices.AllotmentService.getAllotmentInfo();
            inValue.arg0 = arg0;
            inValue.allotmentInformationId = allotmentInformationId;
            WindowsBehdadWebServices.AllotmentService.getAllotmentInfoResponse retVal = ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).getAllotmentInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.getAllotmentInfoResponse> WindowsBehdadWebServices.AllotmentService.AllotmentService.getAllotmentInfoAsync(WindowsBehdadWebServices.AllotmentService.getAllotmentInfo request) {
            return base.Channel.getAllotmentInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AllotmentService.getAllotmentInfoResponse> getAllotmentInfoAsync(WindowsBehdadWebServices.AllotmentService.credential arg0, long allotmentInformationId) {
            WindowsBehdadWebServices.AllotmentService.getAllotmentInfo inValue = new WindowsBehdadWebServices.AllotmentService.getAllotmentInfo();
            inValue.arg0 = arg0;
            inValue.allotmentInformationId = allotmentInformationId;
            return ((WindowsBehdadWebServices.AllotmentService.AllotmentService)(this)).getAllotmentInfoAsync(inValue);
        }
    }
}
