//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsBehdadWebServices.AccountService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidIdentifierTypeException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class accountControlCreateModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNumberField;
        
        private string controlTypeField;
        
        private string identifierTypeField;
        
        private string toDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string controlType {
            get {
                return this.controlTypeField;
            }
            set {
                this.controlTypeField = value;
                this.RaisePropertyChanged("controlType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string identifierType {
            get {
                return this.identifierTypeField;
            }
            set {
                this.identifierTypeField = value;
                this.RaisePropertyChanged("identifierType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string toDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("toDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class credential : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidIdentifierControlTypeException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidDateException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class UnableToAuthenticateException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidCredentialException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class PageSizeIsTooMuchException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class InvalidTransactionException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="com.misc.bis.behdad.service", ConfigurationName="AccountService.AccountService")]
    public interface AccountService {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidIdentifierTypeException), Action="", Name="InvalidIdentifierTypeException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidIdentifierControlTypeException), Action="", Name="InvalidIdentifierControlTypeException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidDateException), Action="", Name="InvalidDateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsBehdadWebServices.AccountService.setAccountControlTypeResponse setAccountControlType(WindowsBehdadWebServices.AccountService.setAccountControlType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.setAccountControlTypeResponse> setAccountControlTypeAsync(WindowsBehdadWebServices.AccountService.setAccountControlType request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.PageSizeIsTooMuchException), Action="", Name="PageSizeIsTooMuchException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsBehdadWebServices.AccountService.getPendingTransactionsResponse getPendingTransactions(WindowsBehdadWebServices.AccountService.getPendingTransactions request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.getPendingTransactionsResponse> getPendingTransactionsAsync(WindowsBehdadWebServices.AccountService.getPendingTransactions request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidDateException), Action="", Name="InvalidDateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.PageSizeIsTooMuchException), Action="", Name="PageSizeIsTooMuchException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidTransactionException), Action="", Name="InvalidTransactionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsBehdadWebServices.AccountService.getBankTransactionsDetailsResponse getBankTransactionsDetails(WindowsBehdadWebServices.AccountService.getBankTransactionsDetails request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.getBankTransactionsDetailsResponse> getBankTransactionsDetailsAsync(WindowsBehdadWebServices.AccountService.getBankTransactionsDetails request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidIdentifierTypeException), Action="", Name="InvalidIdentifierTypeException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidDateException), Action="", Name="InvalidDateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsBehdadWebServices.AccountService.getAccountControlTypeResponse getAccountControlType(WindowsBehdadWebServices.AccountService.getAccountControlType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.getAccountControlTypeResponse> getAccountControlTypeAsync(WindowsBehdadWebServices.AccountService.getAccountControlType request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidIdentifierTypeException), Action="", Name="InvalidIdentifierTypeException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidDateException), Action="", Name="InvalidDateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsBehdadWebServices.AccountService.clearAccountControlTypeResponse clearAccountControlType(WindowsBehdadWebServices.AccountService.clearAccountControlType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.clearAccountControlTypeResponse> clearAccountControlTypeAsync(WindowsBehdadWebServices.AccountService.clearAccountControlType request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.UnableToAuthenticateException), Action="", Name="UnableToAuthenticateException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsBehdadWebServices.AccountService.InvalidCredentialException), Action="", Name="InvalidCredentialException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsBehdadWebServices.AccountService.getAccountNumbersResponse getAccountNumbers(WindowsBehdadWebServices.AccountService.getAccountNumbers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.getAccountNumbersResponse> getAccountNumbersAsync(WindowsBehdadWebServices.AccountService.getAccountNumbers request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setAccountControlType", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class setAccountControlType {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AccountService.credential arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AccountService.accountControlCreateModel arg1;
        
        public setAccountControlType() {
        }
        
        public setAccountControlType(WindowsBehdadWebServices.AccountService.credential arg0, WindowsBehdadWebServices.AccountService.accountControlCreateModel arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setAccountControlTypeResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class setAccountControlTypeResponse {
        
        public setAccountControlTypeResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class paging : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pageNumberField;
        
        private bool pageNumberFieldSpecified;
        
        private int recordCountField;
        
        private bool recordCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
                this.RaisePropertyChanged("pageNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNumberSpecified {
            get {
                return this.pageNumberFieldSpecified;
            }
            set {
                this.pageNumberFieldSpecified = value;
                this.RaisePropertyChanged("pageNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
                this.RaisePropertyChanged("recordCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recordCountSpecified {
            get {
                return this.recordCountFieldSpecified;
            }
            set {
                this.recordCountFieldSpecified = value;
                this.RaisePropertyChanged("recordCountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class pagedData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] currentPageDataField;
        
        private int pageIndexField;
        
        private bool pageIndexFieldSpecified;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private long totalCountField;
        
        private bool totalCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("currentPageData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public object[] currentPageData {
            get {
                return this.currentPageDataField;
            }
            set {
                this.currentPageDataField = value;
                this.RaisePropertyChanged("currentPageData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int pageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
                this.RaisePropertyChanged("pageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageIndexSpecified {
            get {
                return this.pageIndexFieldSpecified;
            }
            set {
                this.pageIndexFieldSpecified = value;
                this.RaisePropertyChanged("pageIndexSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified {
            get {
                return this.pageSizeFieldSpecified;
            }
            set {
                this.pageSizeFieldSpecified = value;
                this.RaisePropertyChanged("pageSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long totalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
                this.RaisePropertyChanged("totalCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCountSpecified {
            get {
                return this.totalCountFieldSpecified;
            }
            set {
                this.totalCountFieldSpecified = value;
                this.RaisePropertyChanged("totalCountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPendingTransactions", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getPendingTransactions {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AccountService.credential arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AccountService.paging arg2;
        
        public getPendingTransactions() {
        }
        
        public getPendingTransactions(WindowsBehdadWebServices.AccountService.credential arg0, string accountNumber, WindowsBehdadWebServices.AccountService.paging arg2) {
            this.arg0 = arg0;
            this.accountNumber = accountNumber;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPendingTransactionsResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getPendingTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AccountService.pagedData @return;
        
        public getPendingTransactionsResponse() {
        }
        
        public getPendingTransactionsResponse(WindowsBehdadWebServices.AccountService.pagedData @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.misc.bis.behdad.service")]
    public partial class accountTransactionFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNumberField;
        
        private string fromDateTimeField;
        
        private string paymentIdentifierField;
        
        private string toDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fromDateTime {
            get {
                return this.fromDateTimeField;
            }
            set {
                this.fromDateTimeField = value;
                this.RaisePropertyChanged("fromDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string paymentIdentifier {
            get {
                return this.paymentIdentifierField;
            }
            set {
                this.paymentIdentifierField = value;
                this.RaisePropertyChanged("paymentIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string toDateTime {
            get {
                return this.toDateTimeField;
            }
            set {
                this.toDateTimeField = value;
                this.RaisePropertyChanged("toDateTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBankTransactionsDetails", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getBankTransactionsDetails {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AccountService.credential arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AccountService.accountTransactionFilter arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AccountService.paging arg2;
        
        public getBankTransactionsDetails() {
        }
        
        public getBankTransactionsDetails(WindowsBehdadWebServices.AccountService.credential arg0, WindowsBehdadWebServices.AccountService.accountTransactionFilter arg1, WindowsBehdadWebServices.AccountService.paging arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBankTransactionsDetailsResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getBankTransactionsDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AccountService.pagedData @return;
        
        public getBankTransactionsDetailsResponse() {
        }
        
        public getBankTransactionsDetailsResponse(WindowsBehdadWebServices.AccountService.pagedData @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountControlType", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getAccountControlType {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AccountService.credential arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identifierType;
        
        public getAccountControlType() {
        }
        
        public getAccountControlType(WindowsBehdadWebServices.AccountService.credential arg0, string accountNumber, string identifierType) {
            this.arg0 = arg0;
            this.accountNumber = accountNumber;
            this.identifierType = identifierType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountControlTypeResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getAccountControlTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getAccountControlTypeResponse() {
        }
        
        public getAccountControlTypeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="clearAccountControlType", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class clearAccountControlType {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AccountService.credential arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identifierType;
        
        public clearAccountControlType() {
        }
        
        public clearAccountControlType(WindowsBehdadWebServices.AccountService.credential arg0, string accountNumber, string identifierType) {
            this.arg0 = arg0;
            this.accountNumber = accountNumber;
            this.identifierType = identifierType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="clearAccountControlTypeResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class clearAccountControlTypeResponse {
        
        public clearAccountControlTypeResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountNumbers", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getAccountNumbers {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsBehdadWebServices.AccountService.credential arg0;
        
        public getAccountNumbers() {
        }
        
        public getAccountNumbers(WindowsBehdadWebServices.AccountService.credential arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountNumbersResponse", WrapperNamespace="com.misc.bis.behdad.service", IsWrapped=true)]
    public partial class getAccountNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.misc.bis.behdad.service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getAccountNumbersResponse() {
        }
        
        public getAccountNumbersResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountServiceChannel : WindowsBehdadWebServices.AccountService.AccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<WindowsBehdadWebServices.AccountService.AccountService>, WindowsBehdadWebServices.AccountService.AccountService {
        
        public AccountServiceClient() {
        }
        
        public AccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AccountService.setAccountControlTypeResponse WindowsBehdadWebServices.AccountService.AccountService.setAccountControlType(WindowsBehdadWebServices.AccountService.setAccountControlType request) {
            return base.Channel.setAccountControlType(request);
        }
        
        public void setAccountControlType(WindowsBehdadWebServices.AccountService.credential arg0, WindowsBehdadWebServices.AccountService.accountControlCreateModel arg1) {
            WindowsBehdadWebServices.AccountService.setAccountControlType inValue = new WindowsBehdadWebServices.AccountService.setAccountControlType();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WindowsBehdadWebServices.AccountService.setAccountControlTypeResponse retVal = ((WindowsBehdadWebServices.AccountService.AccountService)(this)).setAccountControlType(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.setAccountControlTypeResponse> WindowsBehdadWebServices.AccountService.AccountService.setAccountControlTypeAsync(WindowsBehdadWebServices.AccountService.setAccountControlType request) {
            return base.Channel.setAccountControlTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.setAccountControlTypeResponse> setAccountControlTypeAsync(WindowsBehdadWebServices.AccountService.credential arg0, WindowsBehdadWebServices.AccountService.accountControlCreateModel arg1) {
            WindowsBehdadWebServices.AccountService.setAccountControlType inValue = new WindowsBehdadWebServices.AccountService.setAccountControlType();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WindowsBehdadWebServices.AccountService.AccountService)(this)).setAccountControlTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AccountService.getPendingTransactionsResponse WindowsBehdadWebServices.AccountService.AccountService.getPendingTransactions(WindowsBehdadWebServices.AccountService.getPendingTransactions request) {
            return base.Channel.getPendingTransactions(request);
        }
        
        public WindowsBehdadWebServices.AccountService.pagedData getPendingTransactions(WindowsBehdadWebServices.AccountService.credential arg0, string accountNumber, WindowsBehdadWebServices.AccountService.paging arg2) {
            WindowsBehdadWebServices.AccountService.getPendingTransactions inValue = new WindowsBehdadWebServices.AccountService.getPendingTransactions();
            inValue.arg0 = arg0;
            inValue.accountNumber = accountNumber;
            inValue.arg2 = arg2;
            WindowsBehdadWebServices.AccountService.getPendingTransactionsResponse retVal = ((WindowsBehdadWebServices.AccountService.AccountService)(this)).getPendingTransactions(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.getPendingTransactionsResponse> WindowsBehdadWebServices.AccountService.AccountService.getPendingTransactionsAsync(WindowsBehdadWebServices.AccountService.getPendingTransactions request) {
            return base.Channel.getPendingTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.getPendingTransactionsResponse> getPendingTransactionsAsync(WindowsBehdadWebServices.AccountService.credential arg0, string accountNumber, WindowsBehdadWebServices.AccountService.paging arg2) {
            WindowsBehdadWebServices.AccountService.getPendingTransactions inValue = new WindowsBehdadWebServices.AccountService.getPendingTransactions();
            inValue.arg0 = arg0;
            inValue.accountNumber = accountNumber;
            inValue.arg2 = arg2;
            return ((WindowsBehdadWebServices.AccountService.AccountService)(this)).getPendingTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AccountService.getBankTransactionsDetailsResponse WindowsBehdadWebServices.AccountService.AccountService.getBankTransactionsDetails(WindowsBehdadWebServices.AccountService.getBankTransactionsDetails request) {
            return base.Channel.getBankTransactionsDetails(request);
        }
        
        public WindowsBehdadWebServices.AccountService.pagedData getBankTransactionsDetails(WindowsBehdadWebServices.AccountService.credential arg0, WindowsBehdadWebServices.AccountService.accountTransactionFilter arg1, WindowsBehdadWebServices.AccountService.paging arg2) {
            WindowsBehdadWebServices.AccountService.getBankTransactionsDetails inValue = new WindowsBehdadWebServices.AccountService.getBankTransactionsDetails();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            WindowsBehdadWebServices.AccountService.getBankTransactionsDetailsResponse retVal = ((WindowsBehdadWebServices.AccountService.AccountService)(this)).getBankTransactionsDetails(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.getBankTransactionsDetailsResponse> WindowsBehdadWebServices.AccountService.AccountService.getBankTransactionsDetailsAsync(WindowsBehdadWebServices.AccountService.getBankTransactionsDetails request) {
            return base.Channel.getBankTransactionsDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.getBankTransactionsDetailsResponse> getBankTransactionsDetailsAsync(WindowsBehdadWebServices.AccountService.credential arg0, WindowsBehdadWebServices.AccountService.accountTransactionFilter arg1, WindowsBehdadWebServices.AccountService.paging arg2) {
            WindowsBehdadWebServices.AccountService.getBankTransactionsDetails inValue = new WindowsBehdadWebServices.AccountService.getBankTransactionsDetails();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((WindowsBehdadWebServices.AccountService.AccountService)(this)).getBankTransactionsDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AccountService.getAccountControlTypeResponse WindowsBehdadWebServices.AccountService.AccountService.getAccountControlType(WindowsBehdadWebServices.AccountService.getAccountControlType request) {
            return base.Channel.getAccountControlType(request);
        }
        
        public string getAccountControlType(WindowsBehdadWebServices.AccountService.credential arg0, string accountNumber, string identifierType) {
            WindowsBehdadWebServices.AccountService.getAccountControlType inValue = new WindowsBehdadWebServices.AccountService.getAccountControlType();
            inValue.arg0 = arg0;
            inValue.accountNumber = accountNumber;
            inValue.identifierType = identifierType;
            WindowsBehdadWebServices.AccountService.getAccountControlTypeResponse retVal = ((WindowsBehdadWebServices.AccountService.AccountService)(this)).getAccountControlType(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.getAccountControlTypeResponse> WindowsBehdadWebServices.AccountService.AccountService.getAccountControlTypeAsync(WindowsBehdadWebServices.AccountService.getAccountControlType request) {
            return base.Channel.getAccountControlTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.getAccountControlTypeResponse> getAccountControlTypeAsync(WindowsBehdadWebServices.AccountService.credential arg0, string accountNumber, string identifierType) {
            WindowsBehdadWebServices.AccountService.getAccountControlType inValue = new WindowsBehdadWebServices.AccountService.getAccountControlType();
            inValue.arg0 = arg0;
            inValue.accountNumber = accountNumber;
            inValue.identifierType = identifierType;
            return ((WindowsBehdadWebServices.AccountService.AccountService)(this)).getAccountControlTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AccountService.clearAccountControlTypeResponse WindowsBehdadWebServices.AccountService.AccountService.clearAccountControlType(WindowsBehdadWebServices.AccountService.clearAccountControlType request) {
            return base.Channel.clearAccountControlType(request);
        }
        
        public void clearAccountControlType(WindowsBehdadWebServices.AccountService.credential arg0, string accountNumber, string identifierType) {
            WindowsBehdadWebServices.AccountService.clearAccountControlType inValue = new WindowsBehdadWebServices.AccountService.clearAccountControlType();
            inValue.arg0 = arg0;
            inValue.accountNumber = accountNumber;
            inValue.identifierType = identifierType;
            WindowsBehdadWebServices.AccountService.clearAccountControlTypeResponse retVal = ((WindowsBehdadWebServices.AccountService.AccountService)(this)).clearAccountControlType(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.clearAccountControlTypeResponse> WindowsBehdadWebServices.AccountService.AccountService.clearAccountControlTypeAsync(WindowsBehdadWebServices.AccountService.clearAccountControlType request) {
            return base.Channel.clearAccountControlTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.clearAccountControlTypeResponse> clearAccountControlTypeAsync(WindowsBehdadWebServices.AccountService.credential arg0, string accountNumber, string identifierType) {
            WindowsBehdadWebServices.AccountService.clearAccountControlType inValue = new WindowsBehdadWebServices.AccountService.clearAccountControlType();
            inValue.arg0 = arg0;
            inValue.accountNumber = accountNumber;
            inValue.identifierType = identifierType;
            return ((WindowsBehdadWebServices.AccountService.AccountService)(this)).clearAccountControlTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsBehdadWebServices.AccountService.getAccountNumbersResponse WindowsBehdadWebServices.AccountService.AccountService.getAccountNumbers(WindowsBehdadWebServices.AccountService.getAccountNumbers request) {
            return base.Channel.getAccountNumbers(request);
        }
        
        public string[] getAccountNumbers(WindowsBehdadWebServices.AccountService.credential arg0) {
            WindowsBehdadWebServices.AccountService.getAccountNumbers inValue = new WindowsBehdadWebServices.AccountService.getAccountNumbers();
            inValue.arg0 = arg0;
            WindowsBehdadWebServices.AccountService.getAccountNumbersResponse retVal = ((WindowsBehdadWebServices.AccountService.AccountService)(this)).getAccountNumbers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.getAccountNumbersResponse> WindowsBehdadWebServices.AccountService.AccountService.getAccountNumbersAsync(WindowsBehdadWebServices.AccountService.getAccountNumbers request) {
            return base.Channel.getAccountNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsBehdadWebServices.AccountService.getAccountNumbersResponse> getAccountNumbersAsync(WindowsBehdadWebServices.AccountService.credential arg0) {
            WindowsBehdadWebServices.AccountService.getAccountNumbers inValue = new WindowsBehdadWebServices.AccountService.getAccountNumbers();
            inValue.arg0 = arg0;
            return ((WindowsBehdadWebServices.AccountService.AccountService)(this)).getAccountNumbersAsync(inValue);
        }
    }
}
